import './globals.css'
import type { Metadata } from 'next'

import Navbar from '@/components/Navbar'

import Footer from '@/components/Footer';
// import SignIn from '@/app/signIn/page';
// import SignUp from '@/app/signUp/page';
import getCurrentUser from './actions/getCurrentUser';


export const metadata: Metadata = {
  title: '9jaFayre',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className="bg-[#0D0C0A]">
        <div className=''>
          
        <Navbar currentUser={currentUser}/>
        </div>
        {children}
       <Footer/>
        </body>
    </html>
   
  )
}
